-- Migration 006: G7 (admin decision OFFER_ALTERNATIVE + PENDING)
-- Adds ON_HOLD request status and three new approval_logs actions.

ALTER TABLE facility_requests
  MODIFY COLUMN status ENUM(
    'DRAFT','SUBMITTED',
    'WAITING_BIRO_III','REJECTED_BY_BIRO_III',
    'WAITING_WR3_WD3','REJECTED_BY_WR3_WD3',
    'WAITING_ADMIN_UNIT','REVISION_REQUESTED','ON_HOLD',
    'APPROVED','REJECTED','CANCELLED'
  ) NOT NULL;

ALTER TABLE approval_logs
  MODIFY COLUMN action ENUM(
    'REGISTER','LOGIN','SUBMIT',
    'APPROVE_BIRO_III','REJECT_BIRO_III',
    'APPROVE_WR3_WD3','REJECT_WR3_WD3',
    'APPROVE_ADMIN','REJECT_ADMIN',
    'REQUEST_REVISION','RESUBMIT_REVISION',
    'OFFER_ALTERNATIVE','HOLD','RESUME',
    'CANCEL'
  ) NOT NULL;
