-- Campus Facility Booking Schema
-- Run in phpMyAdmin or mysql CLI:
--   CREATE DATABASE campus_facility_booking;
--   USE campus_facility_booking;
--   SOURCE schema.sql;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('PENGURUS','BIRO_III','WR3_WD3','ADMIN_UNIT','SUPER_ADMIN') NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT FALSE,
  userScope ENUM('UNIVERSITAS','FAKULTAS') NULL,
  organizationName VARCHAR(150) NULL,
  phone VARCHAR(30) NULL,
  identityNumber VARCHAR(80) NULL,
  organizationLogoUrl VARCHAR(255) NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS facilities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NOT NULL,
  managingUnit ENUM('BIRO_I','BIRO_IV','PPLK','KRT','LPAIP') NOT NULL DEFAULT 'BIRO_I',
  location VARCHAR(150) NULL,
  capacity INT NULL,
  description TEXT NULL,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_fac_unit (managingUnit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS facility_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  requestCode VARCHAR(50) NOT NULL UNIQUE,
  userId INT NOT NULL,
  facilityId INT NOT NULL,
  activityName VARCHAR(200) NOT NULL,
  organizationName VARCHAR(150) NOT NULL,
  personInCharge VARCHAR(150) NOT NULL,
  identityNumber VARCHAR(80) NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  startDateTime DATETIME NOT NULL,
  endDateTime DATETIME NOT NULL,
  participantCount INT NULL,
  purpose TEXT NOT NULL,
  description TEXT NOT NULL,
  activityScope ENUM('UNIVERSITAS','FAKULTAS') NOT NULL DEFAULT 'UNIVERSITAS',
  additionalNeeds TEXT NULL,
  attachmentUrl VARCHAR(255) NULL,
  signedLetterUrl VARCHAR(255) NULL,
  notes TEXT NULL,
  status ENUM('DRAFT','SUBMITTED','WAITING_BIRO_III','REJECTED_BY_BIRO_III','WAITING_WR3_WD3','REJECTED_BY_WR3_WD3','WAITING_ADMIN_UNIT','REVISION_REQUESTED','ON_HOLD','APPROVED','REJECTED','CANCELLED') NOT NULL,
  currentStep VARCHAR(80) NULL,
  submittedAt DATETIME NULL,
  approvedAt DATETIME NULL,
  rejectedAt DATETIME NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (facilityId) REFERENCES facilities(id),
  INDEX idx_fr_overlap (facilityId, startDateTime, endDateTime, status),
  INDEX idx_fr_user (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS approval_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  requestId INT NOT NULL,
  actorId INT NULL,
  action ENUM('REGISTER','LOGIN','SUBMIT','APPROVE_BIRO_III','REJECT_BIRO_III','APPROVE_WR3_WD3','REJECT_WR3_WD3','APPROVE_ADMIN','REJECT_ADMIN','REQUEST_REVISION','RESUBMIT_REVISION','OFFER_ALTERNATIVE','HOLD','RESUME','CANCEL') NOT NULL,
  fromStatus VARCHAR(80) NULL,
  toStatus VARCHAR(80) NULL,
  note TEXT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (requestId) REFERENCES facility_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (actorId) REFERENCES users(id),
  INDEX idx_al_request (requestId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  link VARCHAR(255) NULL,
  isRead BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id),
  INDEX idx_notif_user_read (userId, isRead)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS facility_blocks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  facilityId INT NULL,
  startDateTime DATETIME NOT NULL,
  endDateTime DATETIME NOT NULL,
  reason VARCHAR(255) NOT NULL,
  createdBy INT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (facilityId) REFERENCES facilities(id) ON DELETE CASCADE,
  FOREIGN KEY (createdBy) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_blocks_facility (facilityId, startDateTime, endDateTime),
  INDEX idx_blocks_range (startDateTime, endDateTime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS facility_bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  requestId INT NOT NULL,
  facilityId INT NOT NULL,
  startDateTime DATETIME NOT NULL,
  endDateTime DATETIME NOT NULL,
  status ENUM('ACTIVE','CANCELLED') DEFAULT 'ACTIVE',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (requestId) REFERENCES facility_requests(id),
  FOREIGN KEY (facilityId) REFERENCES facilities(id),
  INDEX idx_fb_overlap (facilityId, startDateTime, endDateTime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
