-- Seed data (run after schema.sql)
-- NOTE: prefer running `npm run db:seed` which hashes passwords with bcrypt.
-- This SQL file uses a pre-generated bcrypt hash for "password123".
-- bcrypt hash for "password123" (cost 10):
--   $2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2

INSERT INTO facilities (name, category, managingUnit, location, capacity, description) VALUES
 -- BIRO I — Ruang Pembelajaran (per ruangan)
 ('Ruang B.3.1','Ruang Kelas','BIRO_I','Gedung B Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang B.3.2','Ruang Kelas','BIRO_I','Gedung B Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang B.3.3','Ruang Kelas','BIRO_I','Gedung B Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang B.3.4','Ruang Kelas','BIRO_I','Gedung B Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang C.3.7','Ruang Kelas','BIRO_I','Gedung C Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang C.3.8','Ruang Kelas','BIRO_I','Gedung C Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang C.3.9','Ruang Kelas','BIRO_I','Gedung C Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang D.1.1','Ruang Hybrid','BIRO_I','Gedung D Lt.1',40,'Hybrid'),
 ('Ruang D.1.2','Ruang Tutorial','BIRO_I','Gedung D Lt.1',25,'Ruang Tutorial'),
 ('Ruang D.1.3','Ruang Tutorial','BIRO_I','Gedung D Lt.1',25,'Ruang Tutorial'),
 ('Ruang D.2.1','Ruang Kelas','BIRO_I','Gedung D Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang D.2.2','Ruang Kelas','BIRO_I','Gedung D Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang D.2.3','Ruang Kelas','BIRO_I','Gedung D Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang D.2.4','Ruang Kelas','BIRO_I','Gedung D Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang D.2.5','Ruang Kelas','BIRO_I','Gedung D Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang D.3.1','Ruang Kelas','BIRO_I','Gedung D Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang D.3.2','Ruang Kelas','BIRO_I','Gedung D Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang D.3.4','Ruang Kelas','BIRO_I','Gedung D Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang D.3.5','Ruang Kelas','BIRO_I','Gedung D Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang E.1.2','Ruang Kelas','BIRO_I','Gedung E Lt.1',40,'Ruang Kelas Biasa'),
 ('Ruang E.2.1','Ruang Kelas','BIRO_I','Gedung E Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang E.2.2','Ruang Kelas','BIRO_I','Gedung E Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang E.2.3','Ruang Kelas','BIRO_I','Gedung E Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang E.2.4','Ruang Kelas','BIRO_I','Gedung E Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang E.2.5','Ruang Kelas','BIRO_I','Gedung E Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang E.3.1','Ruang Kelas','BIRO_I','Gedung E Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang E.3.2','Ruang Kelas','BIRO_I','Gedung E Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang E.3.3','Ruang Kelas','BIRO_I','Gedung E Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang E.3.4','Ruang Kelas','BIRO_I','Gedung E Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang E.3.5','Ruang Kelas','BIRO_I','Gedung E Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang E.3.6','Ruang Kelas','BIRO_I','Gedung E Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang G.3.4','Ruang Kelas','BIRO_I','Gedung G Lt.3',40,'Ruang Kelas Biasa'),
 ('Ruang H.2.1','Ruang Kelas','BIRO_I','Gedung H Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang H.2.2','Ruang Kelas','BIRO_I','Gedung H Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang H.2.3','Ruang Kelas','BIRO_I','Gedung H Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang H.2.4','Ruang Kelas','BIRO_I','Gedung H Lt.2',40,'Ruang Kelas Biasa'),
 ('Ruang H.2.5','Ruang Kelas','BIRO_I','Gedung H Lt.2',40,'Ruang Kelas Biasa'),
 -- BIRO IV
 ('Ruang H.1.1','Ruangan','BIRO_IV','Gedung H Lt.1',60,'Ruang serbaguna'),
 ('Studio Podcast','Studio','BIRO_IV','Gedung Biro IV',6,'Fasilitas podcast lengkap untuk produksi audio'),
 ('Kamera Foto','Peralatan','BIRO_IV','Inventaris Biro IV',NULL,'Kamera DSLR untuk dokumentasi acara'),
 ('Kamera Streaming','Peralatan','BIRO_IV','Inventaris Biro IV',NULL,'Kamera streaming untuk siaran live'),
 ('Perlengkapan Mikrofon (Biro IV)','Peralatan','BIRO_IV','Inventaris Biro IV',NULL,'Set mikrofon untuk kegiatan dokumentasi'),
 ('Flash Memory','Peralatan','BIRO_IV','Inventaris Biro IV',NULL,'Media penyimpanan untuk transfer data acara'),
 -- PPLK
 ('Proyektor','Peralatan','PPLK','Inventaris PPLK',NULL,'Proyektor untuk presentasi dan kegiatan'),
 ('Laptop (Peminjaman Khusus)','Peralatan','PPLK','Inventaris PPLK',NULL,'Laptop dengan syarat peminjaman khusus'),
 ('Kabel HDMI','Peralatan','PPLK','Inventaris PPLK',NULL,'Kabel HDMI untuk koneksi proyektor/display'),
 ('Speaker Aktif','Peralatan','PPLK','Inventaris PPLK',NULL,'Speaker aktif portabel'),
 ('Soundcard','Peralatan','PPLK','Inventaris PPLK',NULL,'Soundcard untuk produksi audio'),
 ('Mikrofon (PPLK)','Peralatan','PPLK','Inventaris PPLK',NULL,'Mikrofon untuk kegiatan unit/lintas unit'),
 ('Laboratorium Komputer Lantai 2','Laboratorium','PPLK','Gedung Lab Lt.2',40,'Lab komputer utama'),
 ('Lab Komputer A','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer A'),
 ('Lab Komputer B','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer B'),
 ('Lab Komputer C','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer C'),
 ('Lab Komputer D','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer D'),
 ('Lab Komputer E','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer E'),
 ('Lab Komputer F','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer F'),
 ('Lab Komputer G','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer G'),
 ('Lab Komputer H','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer H'),
 ('Lab Komputer I','Laboratorium','PPLK','Gedung Lab',30,'Lab komputer I'),
 -- KRT
 ('Auditorium Koinonia','Auditorium','KRT','Gedung Koinonia',500,'Auditorium utama kampus'),
 ('Ruang Rudi Budiman','Ruang Seminar','KRT','Gedung Utama',80,'Ruang seminar Rudi Budiman'),
 ('Ruang Harun','Ruang Seminar','KRT','Gedung Utama',80,'Ruang seminar Harun'),
 ('Kendaraan','Kendaraan','KRT','Pool Kendaraan KRT',NULL,'Kendaraan operasional kampus'),
 ('Sound System','Peralatan','KRT','Inventaris KRT',NULL,'Sound system untuk acara besar'),
 ('Layar Viewer Proyektor','Peralatan','KRT','Inventaris KRT',NULL,'Layar untuk proyektor'),
 -- LPAIP
 ('Kamera (LPAIP)','Peralatan','LPAIP','Inventaris LPAIP',NULL,'Kamera dokumentasi multimedia'),
 ('Stabilizer Kamera','Peralatan','LPAIP','Inventaris LPAIP',NULL,'Gimbal/stabilizer untuk video shooting'),
 ('Tripod','Peralatan','LPAIP','Inventaris LPAIP',NULL,'Tripod kamera untuk shooting stabil'),
 ('Saramonic','Peralatan','LPAIP','Inventaris LPAIP',NULL,'Mikrofon Saramonic untuk recording audio');

INSERT INTO users (name, email, password, role, isActive, userScope, bureauScope, organizationName, phone, identityNumber) VALUES
 ('Pengurus Demo',  'pengurus@kampus.test',     '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'PENGURUS',    1, NULL,           NULL,      'BEM Universitas', '081234567890', '2021001'),
 ('Biro III Demo', 'biro3@kampus.test',        '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'BIRO_III',    1, NULL,           NULL,      NULL,              '081234567891', NULL),
 ('WR3 Demo',      'wr3@kampus.test',          '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'WR3_WD3',     1, 'UNIVERSITAS',  NULL,      NULL,              '081234567892', NULL),
 ('WD3 Demo',      'wd3@kampus.test',          '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'WR3_WD3',     1, 'FAKULTAS',     NULL,      NULL,              '081234567895', NULL),
 ('Admin Biro I',  'biro1@kampus.test',        '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'ADMIN_UNIT',  1, NULL,           'BIRO_I',  NULL,              '081234567910', NULL),
 ('Admin Biro IV', 'biro4@kampus.test',        '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'ADMIN_UNIT',  1, NULL,           'BIRO_IV', NULL,              '081234567911', NULL),
 ('Admin PPLK',    'pplk@kampus.test',         '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'ADMIN_UNIT',  1, NULL,           'PPLK',    NULL,              '081234567912', NULL),
 ('Admin KRT',     'krt@kampus.test',          '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'ADMIN_UNIT',  1, NULL,           'KRT',     NULL,              '081234567913', NULL),
 ('Admin LPAIP',   'lpaip@kampus.test',        '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'ADMIN_UNIT',  1, NULL,           'LPAIP',   NULL,              '081234567914', NULL),
 ('Super Admin',   'superadmin@kampus.test',   '$2b$10$Aiuc8QfhGjfY9LofaY/iReV38wmtNY4N7e2tQCDZ/3bRsN6NjhkC2', 'SUPER_ADMIN', 1, NULL,           NULL,      NULL,              '081234567894', NULL);
